import type { PCBFootprint, PCBLayoutData } from '../types/pcb';
import type { Point } from '../analysis/boardChecks';
import { getPadBoardCoords } from '../analysis/boardChecks';

/** %FSLAX46Y46*%: coordinates are integers of 1e-6 mm, so nothing may carry a decimal point. */
const SCALE = 1e6;
const DECIMALS = 6;
const FIRST_APERTURE = 10;

export const MASK_EXPANSION_MM = 0.05;
export const SILK_LINE_WIDTH_MM = 0.15;
export const OUTLINE_LINE_WIDTH_MM = 0.1;

export type Aperture = { shape: 'C'; diameter: number } | { shape: 'R'; width: number; height: number };
export type GerberLayerId =
  | 'topCopper' | 'bottomCopper' | 'topMask' | 'bottomMask' | 'topSilk' | 'topPaste' | 'outline';
export interface GerberLayer { id: GerberLayerId; fileFunction: string; contents: string }

interface Draw {
  flash(aperture: Aperture, at: Point): void;
  stroke(width: number, path: Point[]): void;
}

const grid = (mm: number) => Math.round(mm * SCALE);
const coord = (mm: number) => grid(mm).toString();
/** Aperture sizes are snapped to the coordinate grid so 1.6+0.1 cannot define a second D-code. */
const size = (mm: number) => (grid(mm) / SCALE).toFixed(DECIMALS);
const finitePoint = (p: Point) => Number.isFinite(p.x) && Number.isFinite(p.y);
const positive = (v: number) => Number.isFinite(v) && v > 0;

export function apertureSpec(aperture: Aperture): string {
  return aperture.shape === 'C'
    ? `C,${size(aperture.diameter)}`
    : `R,${size(aperture.width)}X${size(aperture.height)}`;
}

const usable = (aperture: Aperture) => aperture.shape === 'C'
  ? positive(aperture.diameter)
  : positive(aperture.width) && positive(aperture.height);

const circle = (diameter: number): Aperture => ({ shape: 'C', diameter });

function emitLayer(fileFunction: string, geometry: (draw: Draw) => void): string {
  const definitions: string[] = [];
  const codes = new Map<string, number>();
  const body: string[] = [];
  let selected = 0;
  const select = (aperture: Aperture) => {
    const spec = apertureSpec(aperture);
    let code = codes.get(spec);
    if (code === undefined) {
      code = FIRST_APERTURE + codes.size;
      codes.set(spec, code);
      definitions.push(`%ADD${code}${spec}*%`);
    }
    if (code !== selected) { body.push(`D${code}*`); selected = code; }
  };
  const at = (p: Point) => `X${coord(p.x)}Y${coord(p.y)}`;
  geometry({
    flash(aperture, point) {
      if (!usable(aperture) || !finitePoint(point)) return;
      select(aperture);
      body.push(`${at(point)}D03*`);
    },
    stroke(width, path) {
      if (!positive(width) || path.length < 2 || !path.every(finitePoint)) return;
      select(circle(width));
      body.push(`${at(path[0])}D02*`, ...path.slice(1).map(p => `${at(p)}D01*`));
    },
  });
  return [
    'G04 Generated by AURA-PCB. Not a design rule check: review in a Gerber viewer before ordering*',
    '%TF.GenerationSoftware,AURA-PCB,Gerber export,1*%',
    `%TF.FileFunction,${fileFunction}*%`,
    '%TF.FilePolarity,Positive*%',
    '%FSLAX46Y46*%',
    'G04 Format 4.6, leading zeros omitted, absolute coordinates, unit mm*',
    '%MOMM*%',
    '%LPD*%',
    'G01*',
    'G04 APERTURE LIST*',
    ...definitions,
    'G04 APERTURE END LIST*',
    ...body,
    'M02*',
    '',
  ].join('\n');
}

/** Closed outline of a footprint body, rotated the same way its pads are. */
export function footprintOutline(fp: PCBFootprint): Point[] {
  const halfWidth = fp.width / 2;
  const halfHeight = fp.height / 2;
  return ([[-1, -1], [1, -1], [1, 1], [-1, 1], [-1, -1]] as const)
    .map(([sx, sy]) => getPadBoardCoords(fp, { relX: sx * halfWidth, relY: sy * halfHeight }));
}

/**
 * The layout model uses screen coordinates (y grows downward from the board's top-left);
 * Gerber uses mathematical orientation. Emitting model y directly mirrors the board and
 * scraps the panel, so every y is reflected about the board outline exactly once, here.
 */
export const toGerberPoint = (boardHeight: number) =>
  (p: Point): Point => ({ x: p.x, y: boardHeight - p.y });

export function buildGerberLayers(layout: PCBLayoutData): GerberLayer[] {
  const flip = toGerberPoint(layout.boardHeight);
  const pads = layout.footprints.flatMap(fp => fp.pads.map(pad => ({ pad, at: flip(getPadBoardCoords(fp, pad)) })));
  const vias = layout.vias.map(via => ({ via, at: flip({ x: via.x, y: via.y }) }));
  const onLayer = (side: 'top' | 'bottom') => layout.traces.filter(trace => trace.layer === side);
  // SMD pads are top-only copper; drilled pads and vias are plated through in this model.
  const reaches = (side: 'top' | 'bottom', holeDiameter: number) => side === 'top' || holeDiameter > 0;

  const copper = (side: 'top' | 'bottom') => (draw: Draw) => {
    for (const trace of onLayer(side)) draw.stroke(trace.width, trace.points.map(flip));
    for (const { pad, at } of pads) if (reaches(side, pad.holeDiameter)) draw.flash(circle(pad.diameter), at);
    for (const { via, at } of vias) draw.flash(circle(via.diameter), at);
  };
  const mask = (side: 'top' | 'bottom') => (draw: Draw) => {
    const opening = (diameter: number) => circle(diameter + 2 * MASK_EXPANSION_MM);
    for (const { pad, at } of pads) if (reaches(side, pad.holeDiameter)) draw.flash(opening(pad.diameter), at);
    for (const { via, at } of vias) draw.flash(opening(via.diameter), at);
  };
  const silk = (draw: Draw) => {
    for (const fp of layout.footprints) draw.stroke(SILK_LINE_WIDTH_MM, footprintOutline(fp).map(flip));
  };
  const paste = (draw: Draw) => {
    for (const { pad, at } of pads) if (pad.holeDiameter === 0) draw.flash(circle(pad.diameter), at);
  };
  const profile = (draw: Draw) => {
    const { boardWidth: w, boardHeight: h } = layout;
    draw.stroke(OUTLINE_LINE_WIDTH_MM, ([[0, 0], [w, 0], [w, h], [0, h], [0, 0]] as const)
      .map(([x, y]) => flip({ x, y })));
  };

  return ([
    ['topCopper', 'Copper,L1,Top', copper('top')],
    ['bottomCopper', 'Copper,L2,Bot', copper('bottom')],
    ['topMask', 'Soldermask,Top', mask('top')],
    ['bottomMask', 'Soldermask,Bot', mask('bottom')],
    ['topSilk', 'Legend,Top', silk],
    ['topPaste', 'Paste,Top', paste],
    ['outline', 'Profile,NP', profile],
  ] as const).map(([id, fileFunction, geometry]) => ({ id, fileFunction, contents: emitLayer(fileFunction, geometry) }));
}
