import type { PCBFootprint, PCBLayoutData, SchematicData } from '../types/pcb';
import type { Point } from '../analysis/boardChecks';
import { getPadBoardCoords } from '../analysis/boardChecks';

/** %FSLAX46Y46*%: coordinates are integers of 1e-6 mm, so nothing may carry a decimal point. */
const SCALE = 1e6;
const DECIMALS = 6;
const FIRST_APERTURE = 10;

export const MASK_EXPANSION_MM = 0.05;
export const SILK_LINE_WIDTH_MM = 0.15;
export const OUTLINE_LINE_WIDTH_MM = 0.1;

export type Aperture = { shape: 'C'; diameter: number } | { shape: 'R'; width: number; height: number };
export type GerberLayerId =
  | 'topCopper' | 'bottomCopper' | 'topMask' | 'bottomMask' | 'topSilk' | 'topPaste' | 'outline';
export interface GerberLayer { id: GerberLayerId; fileFunction: string; contents: string }

interface Draw {
  flash(aperture: Aperture, at: Point): void;
  stroke(width: number, path: Point[]): void;
  /** Filled contour (G36/G37). Used for the body of a copper pour. */
  region(path: Point[]): void;
  /** Dark adds copper, clear removes it from whatever is already there. */
  polarity(dark: boolean): void;
}

const grid = (mm: number) => Math.round(mm * SCALE);
const coord = (mm: number) => grid(mm).toString();
/** Aperture sizes are snapped to the coordinate grid so 1.6+0.1 cannot define a second D-code. */
const size = (mm: number) => (grid(mm) / SCALE).toFixed(DECIMALS);
const finitePoint = (p: Point) => Number.isFinite(p.x) && Number.isFinite(p.y);
const positive = (v: number) => Number.isFinite(v) && v > 0;

export function apertureSpec(aperture: Aperture): string {
  return aperture.shape === 'C'
    ? `C,${size(aperture.diameter)}`
    : `R,${size(aperture.width)}X${size(aperture.height)}`;
}

const usable = (aperture: Aperture) => aperture.shape === 'C'
  ? positive(aperture.diameter)
  : positive(aperture.width) && positive(aperture.height);

const circle = (diameter: number): Aperture => ({ shape: 'C', diameter });

function emitLayer(fileFunction: string, geometry: (draw: Draw) => void): string {
  const definitions: string[] = [];
  const codes = new Map<string, number>();
  const body: string[] = [];
  let selected = 0;
  const select = (aperture: Aperture) => {
    const spec = apertureSpec(aperture);
    let code = codes.get(spec);
    if (code === undefined) {
      code = FIRST_APERTURE + codes.size;
      codes.set(spec, code);
      definitions.push(`%ADD${code}${spec}*%`);
    }
    if (code !== selected) { body.push(`D${code}*`); selected = code; }
  };
  const at = (p: Point) => `X${coord(p.x)}Y${coord(p.y)}`;
  geometry({
    flash(aperture, point) {
      if (!usable(aperture) || !finitePoint(point)) return;
      select(aperture);
      body.push(`${at(point)}D03*`);
    },
    stroke(width, path) {
      if (!positive(width) || path.length < 2 || !path.every(finitePoint)) return;
      select(circle(width));
      body.push(`${at(path[0])}D02*`, ...path.slice(1).map(p => `${at(p)}D01*`));
    },
    region(path) {
      if (path.length < 4 || !path.every(finitePoint)) return;
      // A region carries no aperture, so forget the selection and let the next draw reassert it.
      body.push('G36*', `${at(path[0])}D02*`, ...path.slice(1).map(p => `${at(p)}D01*`), 'G37*');
      selected = 0;
    },
    polarity(dark) {
      body.push(dark ? '%LPD*%' : '%LPC*%');
    },
  });
  return [
    'G04 Generated by AURA-PCB. Not a design rule check: review in a Gerber viewer before ordering*',
    '%TF.GenerationSoftware,AURA-PCB,Gerber export,1*%',
    `%TF.FileFunction,${fileFunction}*%`,
    '%TF.FilePolarity,Positive*%',
    '%FSLAX46Y46*%',
    'G04 Format 4.6, leading zeros omitted, absolute coordinates, unit mm*',
    '%MOMM*%',
    '%LPD*%',
    'G01*',
    'G04 APERTURE LIST*',
    ...definitions,
    'G04 APERTURE END LIST*',
    ...body,
    'M02*',
    '',
  ].join('\n');
}

/** Closed outline of a footprint body, rotated the same way its pads are. */
export function footprintOutline(fp: PCBFootprint): Point[] {
  const halfWidth = fp.width / 2;
  const halfHeight = fp.height / 2;
  return ([[-1, -1], [1, -1], [1, 1], [-1, 1], [-1, -1]] as const)
    .map(([sx, sy]) => getPadBoardCoords(fp, { relX: sx * halfWidth, relY: sy * halfHeight }));
}

/**
 * The layout model uses screen coordinates (y grows downward from the board's top-left);
 * Gerber uses mathematical orientation. Emitting model y directly mirrors the board and
 * scraps the panel, so every y is reflected about the board outline exactly once, here.
 */
export const toGerberPoint = (boardHeight: number) =>
  (p: Point): Point => ({ x: p.x, y: boardHeight - p.y });

export function buildGerberLayers(layout: PCBLayoutData): GerberLayer[] {
  const flip = toGerberPoint(layout.boardHeight);
  const pads = layout.footprints.flatMap(fp => fp.pads.map(pad => ({ pad, at: flip(getPadBoardCoords(fp, pad)) })));
  const vias = layout.vias.map(via => ({ via, at: flip({ x: via.x, y: via.y }) }));
  const onLayer = (side: 'top' | 'bottom') => layout.traces.filter(trace => trace.layer === side);
  // SMD pads are top-only copper; drilled pads and vias are plated through in this model.
  const reaches = (side: 'top' | 'bottom', holeDiameter: number) => side === 'top' || holeDiameter > 0;

  const copper = (side: 'top' | 'bottom') => (draw: Draw) => {
    const pour = layout.pours.find(candidate => candidate.layer === side);
    const x1 = pour ? layout.boardWidth - pour.margin : 0;
    const y1 = pour ? layout.boardHeight - pour.margin : 0;
    if (pour && pour.net && pour.margin >= 0 && positive(pour.clearance) && x1 > pour.margin && y1 > pour.margin) {
      draw.region(([[pour.margin, pour.margin], [x1, pour.margin], [x1, y1], [pour.margin, y1], [pour.margin, pour.margin]] as const)
        .map(([x, y]) => flip({ x, y })));
      // Foreign copper is cleared out of the flood. Same-net copper is left alone, so when it
      // is drawn below it merges with the plane instead of being ringed by a gap.
      const foreign = (net: string | undefined) => (net ?? '') !== pour.net;
      draw.polarity(false);
      for (const trace of onLayer(side)) if (foreign(trace.net)) draw.stroke(trace.width + 2 * pour.clearance, trace.points.map(flip));
      for (const { pad, at } of pads) if (reaches(side, pad.holeDiameter) && foreign(pad.net)) draw.flash(circle(pad.diameter + 2 * pour.clearance), at);
      for (const { via, at } of vias) if (foreign(via.net)) draw.flash(circle(via.diameter + 2 * pour.clearance), at);
      draw.polarity(true);
    }
    for (const trace of onLayer(side)) draw.stroke(trace.width, trace.points.map(flip));
    for (const { pad, at } of pads) if (reaches(side, pad.holeDiameter)) draw.flash(circle(pad.diameter), at);
    for (const { via, at } of vias) draw.flash(circle(via.diameter), at);
  };
  const mask = (side: 'top' | 'bottom') => (draw: Draw) => {
    const opening = (diameter: number) => circle(diameter + 2 * MASK_EXPANSION_MM);
    for (const { pad, at } of pads) if (reaches(side, pad.holeDiameter)) draw.flash(opening(pad.diameter), at);
    for (const { via, at } of vias) draw.flash(opening(via.diameter), at);
  };
  const silk = (draw: Draw) => {
    for (const fp of layout.footprints) draw.stroke(SILK_LINE_WIDTH_MM, footprintOutline(fp).map(flip));
  };
  const paste = (draw: Draw) => {
    for (const { pad, at } of pads) if (pad.holeDiameter === 0) draw.flash(circle(pad.diameter), at);
  };
  const profile = (draw: Draw) => {
    const { boardWidth: w, boardHeight: h } = layout;
    draw.stroke(OUTLINE_LINE_WIDTH_MM, ([[0, 0], [w, 0], [w, h], [0, h], [0, 0]] as const)
      .map(([x, y]) => flip({ x, y })));
  };

  return ([
    ['topCopper', 'Copper,L1,Top', copper('top')],
    ['bottomCopper', 'Copper,L2,Bot', copper('bottom')],
    ['topMask', 'Soldermask,Top', mask('top')],
    ['bottomMask', 'Soldermask,Bot', mask('bottom')],
    ['topSilk', 'Legend,Top', silk],
    ['topPaste', 'Paste,Top', paste],
    ['outline', 'Profile,NP', profile],
  ] as const).map(([id, fileFunction, geometry]) => ({ id, fileFunction, contents: emitLayer(fileFunction, geometry) }));
}

/**
 * Excellon 2, metric, explicit decimal coordinates.
 *
 * No LZ/TZ zero-suppression code is declared: the coordinates carry an explicit decimal
 * point, so there is nothing to suppress, and pairing a suppression code with decimals is
 * precisely what makes a drill file ambiguous to CAM software. Holes use the same reflected
 * Y as the copper layers so that drill and copper register against one another.
 *
 * Every hole in this board model is plated; there are no non-plated features, so no
 * separate NPTH file is produced.
 */
export function buildExcellonDrill(layout: PCBLayoutData): string {
  const flip = toGerberPoint(layout.boardHeight);
  const hits = [
    ...layout.vias
      .filter(via => positive(via.drillDiameter))
      .map(via => ({ diameter: via.drillDiameter, at: flip({ x: via.x, y: via.y }) })),
    ...layout.footprints.flatMap(fp => fp.pads
      .filter(pad => positive(pad.holeDiameter))
      .map(pad => ({ diameter: pad.holeDiameter, at: flip(getPadBoardCoords(fp, pad)) }))),
  ].filter(hit => finitePoint(hit.at));

  // 1 um is far below any fabrication tolerance, so this absorbs float noise without
  // silently merging two drill sizes a designer deliberately kept apart.
  const byTool = new Map<number, Point[]>();
  for (const hit of hits) {
    const size = Math.round(hit.diameter * 1000) / 1000;
    byTool.set(size, [...(byTool.get(size) ?? []), hit.at]);
  }
  const tools = [...byTool.entries()].sort((a, b) => a[0] - b[0]);
  const code = (index: number) => `T${(index + 1).toString().padStart(2, '0')}`;
  const mm = (value: number) => value.toFixed(3);

  return [
    'M48',
    '; Drill file generated by AURA-PCB. Review in a CAM viewer before ordering.',
    '; All holes are plated through (PTH); this board model has no non-plated features.',
    ';FORMAT={-:-/ absolute / metric / decimal}',
    'FMAT,2',
    'METRIC',
    ...tools.map(([diameter], index) => `${code(index)}C${mm(diameter)}`),
    '%',
    'G90',
    'G05',
    ...tools.flatMap(([, points], index) => [code(index), ...points.map(p => `X${mm(p.x)}Y${mm(p.y)}`)]),
    'T0',
    'M30',
    '',
  ].join('\n');
}

/**
 * Pick-and-place centroid, surface-mount parts only. Through-hole parts are not machine
 * placed, and listing them invites a placement run against parts that cannot be placed.
 *
 * Positions carry the same reflected Y as the Gerber and drill files, and rotation is
 * reflected with them: the layout model rotates clockwise in screen coordinates, so the
 * equivalent angle in the y-up fabrication frame is its negation.
 */
export function buildCentroidCsv(layout: PCBLayoutData, schematic?: SchematicData): string {
  const flip = toGerberPoint(layout.boardHeight);
  // Same escaping as the BOM export: a leading formula character must not execute on open.
  const csv = (s: string) => `"${(/^[=+\-@\t\r]/.test(s) ? "'" : '') + s.replaceAll('"', '""')}"`;
  const mm = (value: number) => value.toFixed(3);
  const rows = layout.footprints
    .filter(fp => fp.pads.length > 0 && fp.pads.every(pad => pad.holeDiameter === 0))
    .map(fp => {
      const at = flip({ x: fp.x, y: fp.y });
      const value = schematic?.components.find(component => component.id === fp.componentId)?.value ?? '';
      return [
        csv(fp.id), csv(value), csv(`${fp.type}_${mm(fp.width)}x${mm(fp.height)}`),
        mm(at.x), mm(at.y), mm(((360 - fp.rotation) % 360 + 360) % 360), csv('Top'),
      ].join(',');
    });
  return ['Designator,Value,Package,MidX(mm),MidY(mm),Rotation(deg),Layer', ...rows].join('\r\n');
}

export interface FabricationFile {
  filename: string;
  contents: string;
  type: string;
  description: string;
}

/** States what the package covers so its limits travel with the files, not only the UI. */
function fabricationNotes(): string {
  return [
    'AURA-PCB fabrication output',
    '===========================',
    '',
    'These files describe the two-layer board open in AURA-PCB at export time. They have not',
    'been checked against any fabricator capability profile, and their existence implies no',
    'design rule check. Open every layer in a Gerber viewer and compare it against your design',
    'before placing an order.',
    '',
    'Coordinates',
    '  Gerber: RS-274X, format 4.6, absolute, millimetres, leading zeros omitted.',
    '  Drill:  Excellon 2, metric, absolute, explicit decimal point.',
    '  The origin is the lower-left corner of the board outline. The editor works in screen',
    '  coordinates with Y increasing downward; every file here reflects Y about the board',
    '  height so that it increases upward, as fabrication tooling expects.',
    '',
    'Included',
    '  - Two copper layers, soldermask both sides, top legend, top paste, board outline.',
    `  - Soldermask openings are the pad diameter plus ${MASK_EXPANSION_MM} mm per side.`,
    '  - The legend is footprint body outlines only. This exporter has no stroke font, so no',
    '    reference designators or other silkscreen text are drawn.',
    '  - Copper pours are exported as a filled plane with every other net cleared out of it in',
    '    negative polarity, at the clearance stored with the pour.',
    '  - All drilled holes are treated as plated.',
    '  - The centroid file lists surface-mount parts only.',
    '',
    'Not included',
    '  - No thermal relief. A pad on the pour net joins the plane with solid copper, which is',
    '    harder to hand-solder and can lift a pad on rework.',
    '  - Pours are rectangular and inset from the board outline by a single margin. There are no',
    '    islands, no keep-out zones, and no removal of copper that the plane orphans.',
    '  - Unless a pour covers the reference side of a trace, any impedance shown in the signal',
    '    integrity workspace assumes a plane this board does not actually contain.',
    '  - No controlled-impedance stackup, layer thickness, or material declaration.',
    '  - No non-circular pads: every pad in this model is a circle.',
    '  - No cutouts, slots, castellations, or internal profile features.',
    '  - No electrical test netlist (IPC-D-356).',
    '',
  ].join('\r\n');
}

/** Build every manufacturing file for the board, for inspection or download. */
export function buildFabricationPackage(
  layout: PCBLayoutData,
  projectName: string,
  schematic?: SchematicData,
): FabricationFile[] {
  // Collapsing anything that is not a word character or dash means a project name can never
  // introduce a path separator, a traversal segment, or a leading formula character.
  const base = projectName.replace(/[^\w-]+/g, '-').replace(/^[-.]+|[-.]+$/g, '').slice(0, 64) || 'aura-board';
  const described: Record<GerberLayerId, { ext: string; description: string }> = {
    topCopper: { ext: 'GTL', description: 'Top copper (L1)' },
    bottomCopper: { ext: 'GBL', description: 'Bottom copper (L2)' },
    topMask: { ext: 'GTS', description: 'Top soldermask' },
    bottomMask: { ext: 'GBS', description: 'Bottom soldermask' },
    topSilk: { ext: 'GTO', description: 'Top legend (footprint outlines, no text)' },
    topPaste: { ext: 'GTP', description: 'Top paste stencil (surface-mount pads)' },
    outline: { ext: 'GKO', description: 'Board outline' },
  };
  return [
    ...buildGerberLayers(layout).map(layer => ({
      filename: `${base}.${described[layer.id].ext}`,
      contents: layer.contents,
      type: 'text/plain',
      description: described[layer.id].description,
    })),
    {
      filename: `${base}.DRL`,
      contents: buildExcellonDrill(layout),
      type: 'text/plain',
      description: 'Excellon drill, plated holes and vias',
    },
    {
      filename: `${base}-centroid.csv`,
      contents: buildCentroidCsv(layout, schematic),
      type: 'text/csv',
      description: 'Pick-and-place centroid, surface-mount parts only',
    },
    {
      filename: `${base}-FABRICATION-NOTES.txt`,
      contents: fabricationNotes(),
      type: 'text/plain',
      description: 'What this package does and does not cover',
    },
  ];
}
